### ISSUE TITLE
Host can not shutdown

### ISSUE THREAD

**Issue by spysir** [wxt9861/esxi_stats#100]
![cannot-shutdown](https://github.com/wxt9861/esxi_stats/assets/59646715/11cf0d3b-a63b-4329-bed3-aba806d3cedb)

**Comment by wxt9861** [comment]
You need provide value for force. Under normal behavior, the host will not shutdown unless it is in MM mode.

Service data needs to have the force key
`{"host": "ESX1", "command": "shutdown", "force": true}`
