### ISSUE TITLE
Change cpu_use_% to cpu_use

### ISSUE THREAD

**Issue by oxigenxservices** [wxt9861/esxi_stats#17]
Unfortunately, the attribute named cpu_use_% cannot be used in the Custom Tamplate Sensor integration because it contains the% character and tense cannot be used.

**Comment by wxt9861** [comment]
By Custom Tamplate Sensor integration are you talking about home assistant build in templating or is this a custom component?

**Comment by apedance** [comment]
This should do the trick.

`sensor:
  - platform: template
      esxi_cpuusage:
        friendly_name: "ESXi CPU Usage"
        unit_of_measurement: 'GHz'
        value_template: >-
          {{ states.sensor.esxi_vmhost_{yourhostnamehere}.attributes["cpuusage_ghz"] }}
        icon_template: mdi:chip`

This will template your strings and add the unit to it. Put it in your configuration.yaml

**Comment by wxt9861** [comment]
I still need the OP to answer my question before going forward with a solution.

The above solution or this {{ states.sensor.esxi_vm_<vm_name>["cpu_use_%"] }} works using a regular template, but I don't know if the OP is talking about some other component or what?

**Comment by oxigenxservices** [comment]
I specifically meant this component. https://github.com/custom-components/templatesensor. Configuration are done through the UI and in UI cant use %

**Comment by wxt9861** [comment]
Ok thanks. I can change this to cpu_use_pct and that would be a breaking change for anyone using cpu_use_%, but not a really big deal overall.

**Comment by oxigenxservices** [comment]
It would be good for future integration. The percent sign is not appropriate. Thank you for your response and solution. I personally solved this by changing your code in my HASS.

**Comment by wxt9861** [comment]
Addressed in #19 in released in 0.5.1
