### ISSUE TITLE
Change the update frequency.

### ISSUE THREAD

**Issue by apedance** [wxt9861/esxi_stats#18]
this

**Comment by wxt9861** [comment]
Change it to what? Right now it is set to 60 seconds, I set it to 60s mostly in case someone is monitoring a vcenter with a large (by homelab standards) number of VMs running.

**Comment by apedance** [comment]
I see. Thank you for the insight.
I suppose I need better wording for my request.

Is it possible to make the update frequency user definable?

A configuration option: update_frequency

**Comment by wxt9861** [comment]
Let me see how I can make it work. Updates to follow.

**Comment by apedance** [comment]
Thank you!

**Comment by wxt9861** [comment]
So I don't see how to make this work with config_flows (integration UI) and I can't find any examples of this elsewhere. I'll ask on discord and in the mean time I lowered scan interval to about once every 45 seconds (from 60 seconds). Should be released tomorrow or so.

**Comment by wxt9861** [comment]
Scan interval set to ~45 seconds in #19. When it is clear how to make this use configurable when configured via Integration UI, I will add it.

**Comment by apedance** [comment]
Thank you very much.
