### ISSUE TITLE
Add name of snapshots for VM

### ISSUE THREAD

**Issue by fnoir** [wxt9861/esxi_stats#21]
Could you add the ability to get the name of snapshots ?

When an update is available on HA, I create automatically a snapshot with a unique name. Now, I would like to verify that the snapshot has been created to send me a notification

Thanks

**Comment by wxt9861** [comment]
So the concern with this is what do we do when we have multiple snapshots per VM? Listing all of the snapshot names in an attribute is going to look ugly and could take up a lot of space.

I can add a field to list the name of the last snapshot in a snapshot tree. So if you have 3 snapshots, it will list the name of the latest snapshot.
