### ISSUE TITLE
Plugin fails to start

### ISSUE THREAD

**Issue by vulnersCom** [wxt9861/esxi_stats#28]
Got error starting the plugin, all data is empty.
HASS latest stable, plugin latest master.

Got 3 hosts in cluster, one is down (network connection error) in vCenter.

Hass error log:
Log Details (ERROR)
Logger: custom_components.esxi_stats
Source: custom_components/esxi_stats/__init__.py:146
First occurred: 11:16:26 AM (5 occurrences)
Last logged: 11:17:52 AM

local variable 'host_mm_mode' referenced before assignment

I think it matches the case when there are error offline hypervisors in cluster.

**Comment by wxt9861** [comment]
Can you install version 0.5.1 and confirm it works?

**Comment by vulnersCom** [comment]
Installed.
Still same issue.
<img width="1499" alt="Screenshot 2020-04-13 at 20 39 21" src="https://user-images.githubusercontent.com/22376776/79144043-f5429700-7dc6-11ea-8676-2473702f04fe.png">

**Comment by wxt9861** [comment]
Can you provide the debug log? The screenshot doesn't have any information to help isolate the problem.

**Comment by vulnersCom** [comment]
Easies way to reproduce the problem:
Add 2 hosts to the ESXi cluster.
Restart HA, everything is OK.
Turn one of the host down.
Restart HA, stats will fail to collect.

**Comment by wxt9861** [comment]
Thanks. I only have 1 host making this harder to fix since I need someone else to test each change.

**Comment by vulnersCom** [comment]
Ready to stay on 'master' to make a tests.

**Comment by wxt9861** [comment]
I think this might be fixed in 0.6.3 per #55
