### ISSUE TITLE
2 logs in the newest beta that could improve esxi_stats.

### ISSUE THREAD

**Issue by remb0** [wxt9861/esxi_stats#29]
the newest hass build has improved logging. And that logging comes with 2 logs for esxi_stats:

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:206
First occurred: 8:02:17 (10 occurrences)
Last logged: 8:33:24

esxi_stats: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this
readme: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

and:
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 8:01:42 (2333 occurrences)
Last logged: 8:32:50

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 173: vm_conf = vm.configStatus
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 174: vm_sum = vm.summary
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 175: vm_run = vm.runtime
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 176: vm_snap = vm.snapshot
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 31: current_session = conn.content.sessionManager.currentSession.key

**Comment by wxt9861** [comment]
Hi.  Fix for translations will be available in the next few days. The I/O blocking will take longer as it might require a lot of rewrite and, unfortunately, I don't have as much time right now.
