### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by jscherry** [wxt9861/esxi_stats#35]
**Describe the bug**
this has been ongoing. has anyone ever found a fix? rebooted ha this morning and 6 hours later it shows: 1:54:35 PM – util/async_.py (WARNING) - message first occurred at 8:58:29 AM and shows up 11949 times. running esxi 6.5 using ubuntu 18 vm hassio in docker. logs below:

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 8:58:29 AM (11949 occurrences)
Last logged: 1:54:35 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 173: vm_conf = vm.configStatus
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 174: vm_sum = vm.summary
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 175: vm_run = vm.runtime
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 176: vm_snap = vm.snapshot
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 31: current_session = conn.content.sessionManager.currentSession.key
Successfully saved

**Expected behavior**

**ESXi environment (please complete the following information):**
 - Host/vCenter: ESXi 6.5

**Additional context**

**Comment by Fero1233** [comment]
+1

**Comment by nutinshell** [comment]
+1 Esxi 6.7

**Comment by ciechompl** [comment]
+1

**Comment by sanderlv** [comment]
Hi there, this makes my home assistant very unstable. please let us know if this will get fixed.

No is also an answer then we know if it is worth waiting or delete the integration.

Thank you.

**Comment by wxt9861** [comment]
It will be fixed eventually, but I don't have time to dedicate to this right now. What stability issues are you experiencing exactly?

**Comment by sanderlv** [comment]
See here: https://github.com/wxt9861/esxi_stats/issues/31#issuecomment-651162171

minute after minute is logs errors.

**Comment by gbdesai2004** [comment]
Just reporting the same issue with ESXI 6.7 and the integration, I've uninstalled for now.  Fills up the log quickly and seems to slow down other activities a bit.

**Comment by levickij** [comment]
+1 ESXi 6.7.

**Comment by ntalekt** [comment]
+1 ESXi 7.0

**Comment by christophermichaelshaw** [comment]
+1 ESXi 7.0 HPE edition

**Comment by pjbpaul** [comment]
Hi, Yes I am getting 1000's of errors in the log. Shame I am going to delete the integration. May look at snmp as an alternative. Sorry it did look good. I am on ESXI 6.5 free version.

**Comment by pergolafabio** [comment]
just exclude it from your log

**Comment by shamimrahim** [comment]
+1 ESXI 6.5 and EXSI 7.0.

**Comment by sasukebinbin** [comment]
+1 ESXI 6.7

**Comment by LVM-Mobile** [comment]
+1 
Sorry I'm new with HA development - if it needed ti implement bridge pattern for that?
like here ( https://github.com/home-assistant/core/blob/dev/homeassistant/components/samsungtv/bridge.py )

**Comment by Nihvel** [comment]
Same issue here. And "excluding from the logs" is not an option, it's a really dirty workaround. I prefer seeing millions of rows of errors and knowing there are than being totally blind.
To the author, good job anyway! It's already great that there's a integration for the ESXi.

**Comment by firstof9** [comment]
The PR fixes this. Enjoy!

**Comment by pergolafabio** [comment]
Much appreciated!

**Comment by sasukebinbin** [comment]
> The PR fixes this. Enjoy!

Meaning waiting for next HA update will fix this?

**Comment by pergolafabio** [comment]
no, since its a custom component

**Comment by firstof9** [comment]
> Meaning waiting for next HA update will fix this?

Nope, once @wxt9861 merges it and does a release, you can update via HACS, or just pull the files from the PR.

**Comment by sasukebinbin** [comment]
> > Meaning waiting for next HA update will fix this?
> 
> Nope, once @wxt9861 merges it and does a release, you can update via HACS, or just pull the files from the PR.

I see. So you open the PR and fixed the issue. Now waiting @wxt9861 merge and release. Or I pull the files from the PR to update myself. My understanding correct?

**Comment by firstof9** [comment]
That's correct.

**Comment by wielhelmus** [comment]
Unfortunately the ESXi entities do not update anymore after this fix.

**Comment by pergolafabio** [comment]
yes, seeing same behaviour too, if i start a VM, it doesnt go to running state for instance

**Comment by wxt9861** [comment]
Apologies. Fix should be coming out shortly.

**Comment by firstof9** [comment]
Sorry, I hadn't noticed the non-updating.

**Comment by pergolafabio** [comment]
tested 0.6.1 , now its updating again

**Comment by firstof9** [comment]
Error setting up 2nd entry for 2nd ESXi machine:

```
2021-04-08 07:38:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.202 for esxi_stats
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/esxi_stats/__init__.py", line 113, in async_setup_entry
    hass.data[DOMAIN_DATA][entry]["monitored_conditions"].append("vmhost")
KeyError: '5079f8fda5b630ceec3496404f4986da'
```
