### ISSUE TITLE
Backup ESXi Host Config

### ISSUE THREAD

**Issue by levickij** [wxt9861/esxi_stats#37]
It would be really cool if this component could take and restore backups of the ESXi host config as a GUI within Home Assistant, with similar interface as as the HA addon for taking snapshots.

https://www.virtuallyghetto.com/2013/02/how-to-backup-restore-free-esxi-host.html
https://kb.vmware.com/s/article/2042141

Thanks in advance!

**Comment by wxt9861** [comment]
There is no way to run configuration backup via the python API. The commands used require power CLI or SSH access to the host.
