### ISSUE TITLE
Integration does not show up in Configuration/Integrations

### ISSUE THREAD

**Issue by gcoltharp** [wxt9861/esxi_stats#43]
I installed the repo through HACS
restarted HASS
Went to Configuration/Integrations as per instruction to add the integration
It is not in the list....
The files are there in the custom_components tree
Docs for manual installation are not clear on how to setup in configuration.yaml
I tried adding 
esxi_stats:
  host: 1.1.1.1
  username: bleh
  password: ******

no errors visible but no entities either.

**Comment by wxt9861** [comment]
yaml configuration is no longer supported.

Are you saying that when you install the integration, then go to **configuration > integrations > "+ Add Integration" button** (to add new intergration) you are not seeing ESXi Stats in the list of available integrations you can add?

**Comment by gcoltharp** [comment]
Correct…

**Comment by gcoltharp** [comment]
Went to check again today…and now its there. Not sure why there would be such a delay.

 
Disregard… I have entities now.
