### ISSUE TITLE
Values don't get updated for a long time / leading to unavailable data in Grafana/InfluxDB

### ISSUE THREAD

**Issue by egandro** [wxt9861/esxi_stats#57]
Got this data from Developer Menu

```
sensor.esxi_datastore_datastore1

name: datastore1
type: vmfs
free_space_gb: 47.41
total_space_gb: 110.25
connected_hosts: 1
virtual_machines: 3
unit_of_measurement: Free (GB)
friendly_name: ESXi datastore datastore1

Last changed: August 27, 2021, 1:22:41 AM
Last updated: August 27, 2021, 1:22:41 AM
```

The time is now: August 28, 2021, 5:47:24 PM

So the stats wasn't updated for a very very long time. This doesn't put data into my InfluxDB.

Would it be ok for you, if I add a fixed update intervall e.g. 60 sec into this?

**Comment by wxt9861** [comment]
Sorry, I don't understand why you're doing this.

> Would it be ok for you, if I add a fixed update intervall e.g. 60 sec into this?

The component already updates every 45 seconds, what other 60 second interval are you looking for?

>Last changed: August 27, 2021, 1:22:41 AM
Last updated: August 27, 2021, 1:22:41 AM
The time is now: August 28, 2021, 5:47:24 PM

This is not an error. If your datastore usage did not change, the sensor will not update. This is not driven but the ESXi component, this is a feature of Home Assistant. Home Assistant will not update a sensor whose value or attribute did not change - and why would it? You don't gain anything, instead you end up using more storage by growing your database size having all of that redundant data in there.

It looks like what you did was force a change on the ESXi datastore by writing a 200mb file to it, thus triggering a change in usage and then removing that 200mb file. Given what I said above, I don't really see the point in doing so.

Going back to your original issue - influxDB. I am assuming you're using grafana to make a chart? If so, to solve your problem, you should set **fill** to **previous** under the Group By block

![image](https://user-images.githubusercontent.com/34514130/131229929-18bdd640-862c-4d98-9a7b-27c8aba9990f.png)

This way, your chart will keep the previous value where the value is null and update to a new value when a new value is generated.

**Comment by wxt9861** [comment]
> I semi "solved" that. It looks like that stats only gets updated when the UI was triggered by a refresh button. So I ended up with a super crap solution :(

Sorry - missed this. This could be a bug either in ESXi or pyVmomi SDK. Your solution makes more sense now.

**Comment by egandro** [comment]
Well I debugged this with lots and lots of debug messages.

ESPi sends back the information - Home Assistand wont save sensor data if they are equivalent to the last update.

What the bad script is doing ... add a significant file... trigger whatever updates the UI in ESXi... your driver picks up that - sends the stat to HA ... then the script is triggered again ... it removes the dummy file ... you driver pics it up and HA triggers the update.

That is stupid. But that's how HA works.
