### ISSUE TITLE
Change Power Management Policy

### ISSUE THREAD

**Issue by alfwro13** [wxt9861/esxi_stats#63]
Would it be possible to add option to change ESXI host power policy between Low Power, Balance and High Performance.
This would be very useful with automation (i.e. if host CPU high then change to High Performance.
Someone has already written a py script to achieve that:
https://github.com/lamw/vmware-scripts/blob/master/python/configure_esxi_power_policy.py

**Comment by wxt9861** [comment]
This is available in [0.7.0beta](https://github.com/wxt9861/esxi_stats/releases/tag/0.7.0beta)

**Comment by alfwro13** [comment]
Perfect thanks, tested it - works great!
