### ISSUE TITLE
disable HA notifications

### ISSUE THREAD

**Issue by pathia** [wxt9861/esxi_stats#64]
**Is your feature request related to a problem? Please describe.**
It gets kinda annoying that every time I power on a machine I get a notification in HA.

**Describe the solution you'd like**
Get an option to disable the notifications in HA for the service call to power on/off a machine.

**Describe alternatives you've considered**
?

**Additional context**

**Comment by pathia** [comment]
Awesome, thanks!

**Comment by pathia** [comment]
I am tested it. It seems there's only a small glitch after updating.
At first the integration was unable to start and in the logs it stated something about an unknown key notify. Unfortunately I forgot to copy the error. I'm sorry for that.

After disabling the notification I got rid of the error. And after enabling it again it didn't come back again.
I think perhaps there is no initialization of the new variable notify?

**Comment by DieMetRik** [comment]
Error setting up entry samilyanov.ru for esxi_stats
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/esxi_stats/__init__.py", line 139, in async_setup_entry
    async_add_services(hass, config_entry)
  File "/config/custom_components/esxi_stats/__init__.py", line 298, in async_add_services
    notify = config_entry.options["notify"]
KeyError: 'notify'

This error after update to 0.7 beta2

**Comment by wxt9861** [comment]
The error above should now be addressed in 0.7.0beta7
