### ISSUE TITLE
vim.fault.NoPermission

### ISSUE THREAD

**Issue by Kedryn** [wxt9861/esxi_stats#65]
Don't know is if it's a bug or my fault
I added the ESXi Stats integration to my HA 2022.2.5
In the integration panel, i configured ESXi Stats with the ip of the vCenter, user and password (made a read only user for this integration, as i want only to read statistics), but i got some errors in the logs:

ERROR: 
(vim.fault.NoPermission) { dynamicType = <unset>, dynamicProperty = (vmodl.DynamicProperty) [], msg = '', faultCause = <unset>, faultMessage = (vmodl.LocalizableMessage) [], object = 'vim.LicenseManager:LicenseManager', privilegeId = 'Global.Licenses' }

WARNING: 
Config entry '10.1.101.31' for esxi_stats integration not ready yet: None; Retrying in background

This is the integration screenshot:
![image](https://user-images.githubusercontent.com/12759632/153251099-d26502a8-9526-4eb9-a906-6112e146d96c.png)

 - Host/vCenter: 6.5

I tested the credentials in vSphere 7.0 and were fine.

**Comment by TheGabeMan** [comment]
I know that to be able to read licenses, you need special permissions in vSphere. Maybe esxi_stats wants these permissions as well. Check this post:
https://communities.vmware.com/t5/VMware-vSphere-Discussions/Global-Licenses-privilege-Info/td-p/2278456

**Comment by Kedryn** [comment]
You got it. Thanks
