### ISSUE TITLE
Ability to monitor multiple ESXi servers and license status?

### ISSUE THREAD

**Issue by daphatty** [wxt9861/esxi_stats#7]
Came to say thank you for the excellent custom component. I can't believe how easy it was to get access to these key data points. 

Is there any chance we can add the ability to monitor multiple individual ESXi servers? 

Also, any chance we can add the ability to monitor the license expiration date?

**Comment by wxt9861** [comment]
License monitoring has been added in #10 and part of 0.4.0 release.
