### ISSUE TITLE
Active Memory

### ISSUE THREAD

**Issue by zSprawl** [wxt9861/esxi_stats#73]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Any chance we can change the values it reports for memory for each VM? Right now, it shows memory allocated and memory used. Neither value is really that important. What would really be useful is the current active memory.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by wxt9861** [comment]
This is available in [0.7.0beta3 ](https://github.com/wxt9861/esxi_stats/releases/tag/0.7.0beta3)release

**Comment by zSprawl** [comment]
Work great. Thanks!!!
