### ISSUE TITLE
Total Allocated Storage per VM

### ISSUE THREAD

**Issue by zSprawl** [wxt9861/esxi_stats#74]
**Is your feature request related to a problem? Please describe.**
My apologies for not asking for this when you added total active memory, but I'm hoping we can add the total allocated storage space to the list of attributes for each VM, so we can monitor % free space.

**Describe the solution you'd like**
Ideally we add the total allocated storage for each VM and/or the percentage of disk space, so we can monitor it.

**Describe alternatives you've considered**
Obviously we can use ESXi monitoring for this, but it's nice to have it all in HA.

**Additional context**
None.

**Comment by zSprawl** [comment]
I spent some time yesterday building out my dashboard for my VMs, and I'm not sure this request is going to be as easy as I originally thought since the host monitors the datastores, not the disk usage by the OS itself.

To answer your question, I am using thin provisioning, and I noticed the storage value grows with snapshots as well, so knowing the allocated size is not enough to monitor whether or not the disks themselves are running out of space at the OS level.

I guess in the end, unless you know of some way to pull the disk usage from the OS itself, this request is not feasible.

**Comment by wxt9861** [comment]
I see. Yes, right now you already get space used by the VM as seen by the VMhost/vCenter. As long as vmtools are installed on the OS, we should be able to have some visibility, however OS level specific statistics are outside of the scope of this component.

**Comment by zSprawl** [comment]
Makes sense and completely fair. Thanks for taking the time to respond.
