### ISSUE TITLE
Network Utilization

### ISSUE THREAD

**Issue by zSprawl** [wxt9861/esxi_stats#75]
**Is your feature request related to a problem? Please describe.**
I'm really enjoying this addon, so my apologies if I'm being annoying with requests, but it would be nice to be able to monitor network utilization as well. :)

**Describe the solution you'd like**
Ideally we pull the network in and out values from vCenter/esxi host.

**Describe alternatives you've considered**
I can just use vCenter to monitor things, but I am loving this addon and my new VM dashboard.

**Additional context**
N/A

**Comment by wxt9861** [comment]
These stats are not easily available from the api.
