### ISSUE TITLE
https://github.com/wxt9861/esxi_stats is not a valid add-on repository

### ISSUE THREAD

**Issue by niioannou** [wxt9861/esxi_stats#78]
Hi,
I use HA version 2022.8.6/ Supervisor 2022.08.3/ Operating System 8.4/ Frontend 20220802.0 - latest and I am facing the following error while trying to add it through the Add-On repositories.

I would appreciate for your help.
Nikos

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:123
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 8:54:26 PM (1 occurrences)
Last logged: 8:54:26 PM

Failed to to call /store/repositories - https://github.com/wxt9861/esxi_stats is not a valid add-on repository

**Comment by wxt9861** [comment]
This is a custom component you can add via HACS. This is not an add-on for HASS OS

**Comment by niioannou** [comment]
We are right ... it was my fault.

Eventually, I am running esxi 5.1.0 (799733). Can esxi_stats connect to this version and if yes in what port ?

Thank you

**Comment by wxt9861** [comment]
Officially the package used to communicate with esxi supports versions 6.5+. You can try using this with 5.1, but that version has been end of life for a long time so I don't know. Following the documentation for instructions for installation

**Comment by niioannou** [comment]
Thank you !
