### ISSUE TITLE
Smart Test Triggering and Value Reporting

### ISSUE THREAD

**Issue by EpicLPer** [wxt9861/esxi_stats#81]
**Is your feature request related to a problem? Please describe.**
I'd love to easily gather SMART stats from all drives on an ESXi host to check if a drive may be failing, haven't found a proper solution for this anywhere yet nor have I found anyone else trying it in any automated way that would fit my setup.

**Describe the solution you'd like**
Automatically (or manually) trigger SMART tests periodically to then report and further process by this Custom Component.

**Describe alternatives you've considered**
I've tried using "check_esxi_hardware.py" which apparently should give me some more infos, but even that didn't report what I really wanted. I've also looked into solutions with, as example, Zabbix but even there doesn't seem to be any proper way to get Smart data.

**Additional context**
I have a relatively small Homelab and want to move my main server to my old gaming rig due to the proper Dell Server using way too much power for the performance I'm getting, however it obviously doesn't provide any of the advanced features or monitoring interfaces a proper server has. I haven't used those either tho and would really love to start monitoring for potential failures in the future and not just "let them come at me" :) I've built a few custom Monitoring solutions via NodeRed so far to inform me of a few things, but SMART data is something I'm still missing on a few systems.

**Comment by wxt9861** [comment]
ESXi does not provide smart data via the API.
