### ISSUE TITLE
Memory_used_mb vs memory_allocated_mb vs real life

### ISSUE THREAD

**Issue by lukaszzyla** [wxt9861/esxi_stats#86]
Hi,
I am not sure whether this is a bug or intended operation, but it leaves me somehow unhappy.
In my case, both memory sensors (allocated and used) show almost same values with mem used being slightly bigger.
This results in having 2 memory reading, but none close to what the vms really use:
Like here:
ESXI_STATS:
name: chw-haos
status: green
state: running
uptime_hours: 232
cpu_count: 2
cpu_use_pct: 2.49
memory_allocated_mb: 4096
memory_used_mb: 4129
used_space_gb: 8.67
tools_status: toolsOk
guest_os: Other 5.x Linux (64-bit)
guest_ip: x.x.x.x
snapshots: 0
unit_of_measurement: Cpu Use Pct
friendly_name: ESXi vm chw-haos

While real memory use from within the vm is 0.6GB
![image](https://github.com/wxt9861/esxi_stats/assets/36972413/744945cd-87a8-4242-bb47-01505982051d)

This is not HA only - the same values I get for ubuntu vm:
name: chw_ubuntu
status: green
state: running
uptime_hours: 329.3
cpu_count: 16
cpu_use_pct: 0.46
memory_allocated_mb: 16384
memory_used_mb: 16495
used_space_gb: 80.11
tools_status: toolsOk
guest_os: Ubuntu Linux (64-bit)

**Comment by wxt9861** [comment]
``memory_allocated_mb`` - shows how much memory you have allocated to the virtual machine, it is similar to cpu_count which shows how many CPUs are allocated to the virtual machine.

``memory_used_mb`` - shows host memory utilization statistics, in MB. This is also known as consumed host memory. This is between 0 and the configured resource limit. Valid while the virtual machine is running. This includes the overhead memory of the VM.

So as you can see, these are 2 different stats. memory_used_mb is runtime specific, while memory_allocated_mb is configuration item.

That being said, you also have to keep in mind, memory_used_mb are statistics reported from the host perspective, it is not reporting memory usages inside of the VM.

[0.7.0 beta](https://github.com/wxt9861/esxi_stats/releases/tag/0.7.0beta7) introduces another memory statistic:
``memory_active_mb`` - shows guest memory utilization statistics, in MB. This is also known as active guest memory. The number can be between 0 and the configured memory size of the virtual machine. Valid while the virtual machine is running.
