### ISSUE TITLE
Incomplete list of sensors available

### ISSUE THREAD

**Issue by gmsiegel** [wxt9861/esxi_stats#88]
**Describe the bug**
The integration is setup. However, there are only 9 entities appearing, and most of them are the guest VM sensors. For example, I don't see a sensor for cpuusage, memusage, etc.

**Expected behavior**
I spoke with another user who says they have 46 entities appearing.

**Screenshots**

**ESXi environment (please complete the following information):**
 - Host: ESXi 7.0 U3 standalone
- 
**Additional context**
See screenshots
![image](https://github.com/wxt9861/esxi_stats/assets/76663526/6dfafa86-9d79-4f6f-8ca2-379bac2187cd)
![image](https://github.com/wxt9861/esxi_stats/assets/76663526/b0976efe-3d33-42dd-8941-a7ceedf541dc)
![image](https://github.com/wxt9861/esxi_stats/assets/76663526/55e23bc5-1d9c-4d67-8108-f626ea475528)
![image](https://github.com/wxt9861/esxi_stats/assets/76663526/aecfedc2-0bb6-499a-a320-ffe0b786b018)

**Comment by wxt9861** [comment]
Looks correct to me. There are no individual sensors for cpu or mem usage, those are attributes within the sensors.

**Comment by gmsiegel** [comment]
If I wanted to reveal those attributes as sensors (i.e., to add to dashboard cards), woud I need to create custom template sensors?

**Comment by wxt9861** [comment]
Yes, you can create template sensors to break out attributes into their own sensors.
