### ISSUE TITLE
Display CPU stats and CPU temperature of ESXI in HA

### ISSUE THREAD

**Issue by Niriuqq** [wxt9861/esxi_stats#98]
Hello together

I am new to the HA community and wanted to ask how exactly I can use this integration in my Home Assistant Dashboard to display how busy the CPU is or how high the CPU temperature of the ESXI host is.

With my current installation, I only see these entities:
![image](https://github.com/wxt9861/esxi_stats/assets/113716635/9d09f732-3e99-438c-8283-87cb4944c173)

Thank you for your help

**Comment by wxt9861** [comment]
CPU usage is already captured as an attribute of the vmhost sensor. The temperature readings depend on IPMI capabilities, which might or might not be present and which is something the component does not check for at the moment.

**Comment by Niriuqq** [comment]
Hi thank you very much. I don't necessarily need the CPU temperature either. But how do I display this CPU usage in the dashboard? Do I have to adjust something in the yaml file?

**Comment by wxt9861** [comment]
You can look at the documentation in this repo for some examples or you can refer to Home Assistant documentation for how to present sensor attributes in lovelace.
